---
name: pages
'on':
  push:
    branches: '*'
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Ensure codebase is present
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Ensure codebase is pushed to cloudflare pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          branch: main
          directory: '.'
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
...
